name: cut-prerelease
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  cut:
    uses: compliance-framework/workflows/.github/workflows/cut-prerelease.yml@21aaac7c174aaf90abafecf1c90c30b238367d3d # v1.3.1
    permissions:
      contents: read
    secrets: inherit
