name: cut-prerelease
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  cut:
    uses: compliance-framework/workflows/.github/workflows/cut-prerelease.yml@ec58cea2c02f12b5dad6b23a7bfdc84360f59f11 # v1.3.0
    permissions:
      contents: read
    secrets: inherit
